services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - planit-network
      
  cron_jobs:
    build: ./cron_jobs
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - APPWRITE_ENDPOINT=${APPWRITE_ENDPOINT}
      - APPWRITE_PROJECT_ID=${APPWRITE_PROJECT_ID}
      - APPWRITE_API_KEY=${APPWRITE_API_KEY}
      - APPWRITE_DATABASE_ID=${APPWRITE_DATABASE_ID}
      - APPWRITE_TASKS_COLLECTION=${APPWRITE_TASKS_COLLECTION}
      - MESSAGING_QUEUE_URL=${MESSAGING_QUEUE_URL}
      - MESSAGING_QUEUE_HEALTH_URL=${MESSAGING_QUEUE_HEALTH_URL}
    depends_on:
      - redis
    networks:
      - planit-network